NAME="Orange OS"
VERSION="0.2.0"
PLATFORM="xnu++"
MODE="cli"

PREFIX="/usr/local"

STATE_ROOT="/var/lib/orange"
PACKAGE_ROOT="/var/lib/orange/packages"
PACKAGE_DB="/var/lib/orange/packages.db"
LOG_ROOT="/var/log/orange"

SERVICE_ROOT="/etc/orange/services"
SERVICE_STATE="/var/lib/orange/services"

DESKTOP="kde-plasma"
DISPLAY_SERVER="wayland"
